export enum AuthError {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  NOT_AUTHORIZED = 'NOT_AUTHORIZED',
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  USER_ALREADY_EXIST = 'USER_ALREADY_EXIST',
  NO_TOKEN_ACCEPTED = 'NO_TOKEN_ACCEPTED',
  INVALID_TOKEN = 'INVALID_TOKEN'
}